# Generated by Django 4.2.11 on 2024-04-07 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='archived',
            field=models.BooleanField(default=False, help_text='Indicates if the project has been archived.'),
        ),
    ]
